import type { Monkey } from "./types";

const img = (name: string) => `/monkeys/${name}.jpg`;

/**
 * Sample nursery shown while Supabase is not configured yet (and seeded into
 * the database by supabase/schema.sql). The photos are the owner's own, stored
 * in /public/monkeys. Delete these from the dashboard once real listings with
 * real photos are uploaded.
 */
export const sampleMonkeys: Monkey[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    slug: "pip-common-marmoset",
    name: "Pip",
    species: "Common Marmoset",
    gender: "male",
    markings: "Silver-agouti with white ear tufts",
    date_of_birth: "2026-06-02",
    price: 3800,
    description:
      "Pip follows us from room to room. He is the first to climb onto a shoulder and the last to let go. We have raised him in our living room since he was three weeks old. He takes his formula without a fuss and chirps a greeting when he hears the kitchen door. He shares a hammock with his sister and would settle well into a calm home where someone is around.",
    temperament: "Curious, chatty, very attached to his people",
    vaccinated: true,
    diaper_trained: true,
    hand_raised: true,
    health_notes:
      "Two exotic-vet wellness exams complete, fecal screen clear, weight gain on target. Comes with full vet records, a feeding schedule, and two weeks of his current formula.",
    status: "available",
    featured: true,
    images: [img("marmoset-twins"), img("marmoset-trio")],
    created_at: "2026-08-20T10:00:00Z",
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    slug: "willow-common-marmoset",
    name: "Willow",
    species: "Common Marmoset",
    gender: "female",
    markings: "Warm brindle with a banded tail",
    date_of_birth: "2026-06-02",
    price: 4100,
    description:
      "Willow is Pip's sister and the gentler of the pair. She watches a new room carefully before she commits to it, then explores every inch of it. She loves mealworm treats, warm blankets, and being carried in a chest pouch while the household goes about its day. Marmosets thrive in company, so we would happily discuss a discount if she goes home with her brother.",
    temperament: "Gentle, watchful, affectionate once she settles",
    vaccinated: true,
    diaper_trained: true,
    hand_raised: true,
    health_notes:
      "Exotic-vet checked twice, fecal screen clear, supplemented with D3 and calcium since weaning. Full records travel with her.",
    status: "available",
    featured: true,
    images: [img("marmoset-duo"), img("marmoset-portrait")],
    created_at: "2026-08-20T10:05:00Z",
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    slug: "twiggy-pygmy-marmoset",
    name: "Twiggy",
    species: "Pygmy Marmoset",
    gender: "female",
    markings: "Tawny-olive, ringed tail",
    date_of_birth: "2026-06-24",
    price: 4600,
    description:
      "Twiggy is the smallest monkey we have. She fits in the palm of a hand and weighs less than a bar of soap. Pygmy marmosets are what people mean by finger monkeys: tiny, quick, and busy all day. She is fully weaned onto gum, fruit and insects, and she has the boldest character here in the smallest body.",
    temperament: "Bold, quick, afraid of nothing",
    vaccinated: true,
    diaper_trained: false,
    hand_raised: true,
    health_notes:
      "Wellness exam at ten weeks, dewormed, doing well on a gum and insect diet. She comes with detailed care notes. Pygmy marmosets need specialist care and we talk every family through it.",
    status: "available",
    featured: false,
    images: [img("marmoset-palm"), img("marmoset-hand")],
    created_at: "2026-08-21T09:00:00Z",
  },
  {
    id: "00000000-0000-4000-8000-000000000004",
    slug: "mango-brown-capuchin",
    name: "Mango",
    species: "Brown Capuchin",
    gender: "male",
    markings: "Cinnamon coat, cream face",
    date_of_birth: "2026-05-11",
    price: 8200,
    description:
      "Mango is the joker here. He has worked out how to open the treat tin, undo a zipper, and convince every visitor that nobody has fed him. He is bottle-raised, wears a diaper without complaint, and falls asleep on someone's chest most afternoons. A capuchin is a twenty to forty year commitment, so Mango needs a family who has thought that far ahead.",
    temperament: "Clever, mischievous, very affectionate",
    vaccinated: true,
    diaper_trained: true,
    hand_raised: true,
    health_notes:
      "Full exotic-vet workup, age-appropriate vaccinations, negative TB test, dewormed. Microchipped before he goes home, with a copy of his health certificate for interstate transport.",
    status: "available",
    featured: true,
    images: [img("capuchin-pink-teddy"), img("capuchin-baby")],
    created_at: "2026-08-22T11:00:00Z",
  },
  {
    id: "00000000-0000-4000-8000-000000000005",
    slug: "biscuit-brown-capuchin",
    name: "Biscuit",
    species: "Brown Capuchin",
    gender: "female",
    markings: "Golden-brown with a dark cap",
    date_of_birth: "2026-05-11",
    price: 8600,
    description:
      "Biscuit is Mango's littermate and the steadier of the two. She is the one who sits quietly with a soft toy while the others tear around, and she has the sweetest habit of holding a finger while she drinks her bottle. She is excellent with calm dogs and has never once nipped a handler.",
    temperament: "Calm, patient, loves being held",
    vaccinated: true,
    diaper_trained: true,
    hand_raised: true,
    health_notes:
      "Exotic-vet checked, vaccinations current, negative TB test, dewormed. Health certificate issued within 10 days of travel.",
    status: "reserved",
    featured: false,
    images: [img("capuchin-blue-teddy"), img("capuchin-trio")],
    created_at: "2026-08-22T11:10:00Z",
  },
  {
    id: "00000000-0000-4000-8000-000000000006",
    slug: "pearl-white-faced-capuchin",
    name: "Pearl",
    species: "White-faced Capuchin",
    gender: "female",
    markings: "Cream mantle, black body",
    date_of_birth: "2026-04-28",
    price: 9400,
    description:
      "Pearl has the cream shoulders and pale face of a white-faced capuchin, and she carries herself like she knows it. She is confident with new people, travels well, and already answers to her name and to a hand signal for come. She is rewarding company and hard work in equal measure.",
    temperament: "Confident, expressive, easy to train",
    vaccinated: true,
    diaper_trained: true,
    hand_raised: true,
    health_notes:
      "Two wellness exams, vaccinations current, negative TB test, dewormed, microchipped. Parents both nursery-raised and health-screened.",
    status: "available",
    featured: true,
    images: [img("white-faced-capuchins"), img("capuchin-plush")],
    created_at: "2026-08-23T14:00:00Z",
  },
  {
    id: "00000000-0000-4000-8000-000000000007",
    slug: "nova-spider-monkey",
    name: "Nova",
    species: "Spider Monkey",
    gender: "female",
    markings: "Black with a pale mask and chest",
    date_of_birth: "2026-04-05",
    price: 11500,
    description:
      "Nova is all arms, legs and tail. She can hang from a curtain rail by her tail alone while eating a grape with both hands. She is the most affectionate monkey we have raised and will wrap all four limbs and her tail around whoever is closest. She needs real height to climb in and a family that is home most of the day.",
    temperament: "Athletic, affectionate, into everything",
    vaccinated: true,
    diaper_trained: true,
    hand_raised: true,
    health_notes:
      "Full exotic-vet workup, vaccinations current, negative TB test, dewormed, microchipped. Written health guarantee and transport health certificate included.",
    status: "available",
    featured: false,
    images: [img("spider-monkey-portrait"), img("spider-monkey-bag")],
    created_at: "2026-08-24T08:30:00Z",
  },
  {
    id: "00000000-0000-4000-8000-000000000008",
    slug: "rio-spider-monkey",
    name: "Rio",
    species: "Spider Monkey",
    gender: "male",
    markings: "Jet black with a tan saddle",
    date_of_birth: "2026-03-19",
    price: 12200,
    description:
      "Rio is the oldest baby here and the most settled. He is used to car rides and vet visits. He rides in a harness, naps in a sling, and always seems to notice when someone is upset. He walks on a lead and has met dogs, children and a very patient parrot without any trouble.",
    temperament: "Easy-going, used to travel, reads people well",
    vaccinated: true,
    diaper_trained: true,
    hand_raised: true,
    health_notes:
      "Vaccinations current, negative TB test, dewormed, microchipped, two clean wellness exams. Harness-trained and crate-conditioned for travel.",
    status: "available",
    featured: false,
    images: [img("spider-monkey-pair"), img("spider-monkey-carseat")],
    created_at: "2026-08-25T16:45:00Z",
  },
  {
    id: "00000000-0000-4000-8000-000000000009",
    slug: "sunny-squirrel-monkey",
    name: "Sunny",
    species: "Squirrel Monkey",
    gender: "male",
    markings: "Olive body, gold limbs, white mask",
    date_of_birth: "2026-06-14",
    price: 5900,
    description:
      "Sunny has a gold and olive coat and never stops. Squirrel monkeys are the busiest monkeys we raise. He is awake, moving and getting into things from sunrise, then sleeps hard in a fleece pouch by early evening. He gets on well with our house dog and would suit a lively, patient household.",
    temperament: "Busy, bright, friendly with everyone",
    vaccinated: true,
    diaper_trained: false,
    hand_raised: true,
    health_notes:
      "Wellness exam at eight weeks, dewormed, fecal screen clear, on a vitamin-D-supplemented diet. Full records and a detailed feeding plan travel with him.",
    status: "available",
    featured: false,
    images: [img("squirrel-monkey-cuddle"), img("monkeys-and-dog")],
    created_at: "2026-08-26T10:15:00Z",
  },
  {
    id: "00000000-0000-4000-8000-000000000010",
    slug: "ollie-macaque",
    name: "Ollie",
    species: "Macaque",
    gender: "male",
    markings: "Chestnut coat, pale muzzle",
    date_of_birth: "2026-06-30",
    price: 6800,
    description:
      "Ollie came to us at two weeks old and has been bottle-raised alongside his brother ever since. He will do anything for food, which makes him easy to train, and he sleeps through the night in a warmed pouch. Macaques are restricted in many states. We check the rules where you live before accepting any reservation.",
    temperament: "Motivated by food, easy to train, close to his brother",
    vaccinated: true,
    diaper_trained: true,
    hand_raised: true,
    health_notes:
      "Exotic-vet checked, vaccinations age-appropriate, negative TB test, dewormed. Legal eligibility confirmed with each buyer before a reservation is accepted.",
    status: "rehomed",
    featured: false,
    images: [img("macaque-babies"), img("howler-hug")],
    created_at: "2026-08-27T09:20:00Z",
  },
];
